all: rand.sys read.exe

read.exe: read.c
  tcc read.c

rand.sys: rand.obj
  tlink /t rand.obj,rand.sys

rand.obj: rand.asm
  tasm /w2 rand.asm

clean:
  del rand.obj
  del rand.sys
  del read.exe
